spring:
  main:
    web-application-type: none
  application:
    name: budgetor
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:budgetor}
    username: ${POSTGRES_USER:budgetor}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: ${OLLAMA_MODEL:mistral}

logging:
  file:
    name: logs/application.log

server:

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:budgetor_bot}
    token: ${TELEGRAM_BOT_TOKEN}
